worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8081

grpc-server-port: 50052

# change to URI of your postgres database
pg-connection: postgresql://user:user@postgres-games:5432/playhub-games
# env-file: /app/.env
